# Generated by Django 2.0 on 2022-03-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_auto_20220308_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='companyid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='company',
            new_name='companyid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='company',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
