# Generated by Django 2.0 on 2022-03-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_auto_20220309_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.Vehicle'),
        ),
    ]
