# Generated by Django 2.0 on 2022-03-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_auto_20220309_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='milage',
            new_name='mileage',
        ),
        migrations.RemoveField(
            model_name='company',
            name='numberofvehicles',
        ),
    ]
