# Generated by Django 4.0.2 on 2022-02-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(to='Tracking.User'),
        ),
    ]
