# Generated by Django 4.0.2 on 2022-02-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_user_is_admin_remove_company_user_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
