# Generated by Django 4.0.2 on 2022-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Blg', max_length=100),
        ),
    ]
