# Generated by Django 4.0.2 on 2022-03-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0008_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
