# Generated by Django 4.0.2 on 2022-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0010_delete_user_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
