# Generated by Django 2.0 on 2022-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_auto_20220309_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='axisaccelerometer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='co2sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='datalogger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='fuelsensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='humiditysensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='obdscanner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='temperaturessensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='weightsensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='serialno',
            field=models.CharField(max_length=100),
        ),
    ]
