# Generated by Django 2.0 on 2022-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_auto_20220310_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='fuelsensor',
        ),
        migrations.AddField(
            model_name='sensingdata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
