# Generated by Django 2.0 on 2022-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0005_auto_20220315_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensingdata',
            old_name='imienumber',
            new_name='imeinumber',
        ),
    ]
