# Generated by Django 2.0 on 2022-03-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_auto_20220315_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensingdata',
            old_name='imeinumber',
            new_name='device',
        ),
    ]
